export const homeObjOne = {
  id: "Reglas",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "Indomita Club",
  headLine: "Club Rules:",
  regla1: "1.Nobody talks about the Indómita Club",
  regla2: "2.No one invites anyone to Indómita Club",
  regla3: "3.You will respect your brothers from the club.",
  imgStart: true,
  dark: true,
  primary: true,
  darkText: false,
};
